/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CreateOrgRouteImport } from './routes/create-org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugDashboardRouteRouteImport } from './routes/$slug/dashboard/route'
import { Route as SlugDashboardIndexRouteImport } from './routes/$slug/dashboard/index'
import { Route as ApiOrgSplatRouteImport } from './routes/api/org/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugDashboardTodosRouteImport } from './routes/$slug/dashboard/todos'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrgRoute = CreateOrgRouteImport.update({
  id: '/create-org',
  path: '/create-org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugDashboardRouteRoute = SlugDashboardRouteRouteImport.update({
  id: '/$slug/dashboard',
  path: '/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugDashboardIndexRoute = SlugDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugDashboardRouteRoute,
} as any)
const ApiOrgSplatRoute = ApiOrgSplatRouteImport.update({
  id: '/api/org/$',
  path: '/api/org/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugDashboardTodosRoute = SlugDashboardTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => SlugDashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-org': typeof CreateOrgRoute
  '/sign-in': typeof SignInRoute
  '/$slug/dashboard': typeof SlugDashboardRouteRouteWithChildren
  '/$slug/dashboard/todos': typeof SlugDashboardTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/dashboard/': typeof SlugDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-org': typeof CreateOrgRoute
  '/sign-in': typeof SignInRoute
  '/$slug/dashboard/todos': typeof SlugDashboardTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/dashboard': typeof SlugDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-org': typeof CreateOrgRoute
  '/sign-in': typeof SignInRoute
  '/$slug/dashboard': typeof SlugDashboardRouteRouteWithChildren
  '/$slug/dashboard/todos': typeof SlugDashboardTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/dashboard/': typeof SlugDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-org'
    | '/sign-in'
    | '/$slug/dashboard'
    | '/$slug/dashboard/todos'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-org'
    | '/sign-in'
    | '/$slug/dashboard/todos'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/create-org'
    | '/sign-in'
    | '/$slug/dashboard'
    | '/$slug/dashboard/todos'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOrgRoute: typeof CreateOrgRoute
  SignInRoute: typeof SignInRoute
  SlugDashboardRouteRoute: typeof SlugDashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrgSplatRoute: typeof ApiOrgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-org': {
      id: '/create-org'
      path: '/create-org'
      fullPath: '/create-org'
      preLoaderRoute: typeof CreateOrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/dashboard': {
      id: '/$slug/dashboard'
      path: '/$slug/dashboard'
      fullPath: '/$slug/dashboard'
      preLoaderRoute: typeof SlugDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/dashboard/': {
      id: '/$slug/dashboard/'
      path: '/'
      fullPath: '/$slug/dashboard/'
      preLoaderRoute: typeof SlugDashboardIndexRouteImport
      parentRoute: typeof SlugDashboardRouteRoute
    }
    '/api/org/$': {
      id: '/api/org/$'
      path: '/api/org/$'
      fullPath: '/api/org/$'
      preLoaderRoute: typeof ApiOrgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/dashboard/todos': {
      id: '/$slug/dashboard/todos'
      path: '/todos'
      fullPath: '/$slug/dashboard/todos'
      preLoaderRoute: typeof SlugDashboardTodosRouteImport
      parentRoute: typeof SlugDashboardRouteRoute
    }
  }
}

interface SlugDashboardRouteRouteChildren {
  SlugDashboardTodosRoute: typeof SlugDashboardTodosRoute
  SlugDashboardIndexRoute: typeof SlugDashboardIndexRoute
}

const SlugDashboardRouteRouteChildren: SlugDashboardRouteRouteChildren = {
  SlugDashboardTodosRoute: SlugDashboardTodosRoute,
  SlugDashboardIndexRoute: SlugDashboardIndexRoute,
}

const SlugDashboardRouteRouteWithChildren =
  SlugDashboardRouteRoute._addFileChildren(SlugDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOrgRoute: CreateOrgRoute,
  SignInRoute: SignInRoute,
  SlugDashboardRouteRoute: SlugDashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrgSplatRoute: ApiOrgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
