/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AuthedRouteRouteRouteImport } from './routes/authed-route/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteTestRouteImport } from './routes/authed-route/test'
import { Route as ApiOrgSplatRouteImport } from './routes/api/org/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SlugdashboardDashboardRouteImport } from './routes/$slug/(dashboard)/dashboard'
import { Route as SlugdashboardDashboardIndexRouteImport } from './routes/$slug/(dashboard)/dashboard.index'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRouteRoute = AuthedRouteRouteRouteImport.update({
  id: '/authed-route',
  path: '/authed-route',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteTestRoute = AuthedRouteTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthedRouteRouteRoute,
} as any)
const ApiOrgSplatRoute = ApiOrgSplatRouteImport.update({
  id: '/api/org/$',
  path: '/api/org/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugdashboardDashboardRoute = SlugdashboardDashboardRouteImport.update({
  id: '/$slug/(dashboard)/dashboard',
  path: '/$slug/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugdashboardDashboardIndexRoute =
  SlugdashboardDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SlugdashboardDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authed-route': typeof AuthedRouteRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/authed-route/test': typeof AuthedRouteTestRoute
  '/$slug/dashboard': typeof SlugdashboardDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/dashboard/': typeof SlugdashboardDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authed-route': typeof AuthedRouteRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/authed-route/test': typeof AuthedRouteTestRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/dashboard': typeof SlugdashboardDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authed-route': typeof AuthedRouteRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/authed-route/test': typeof AuthedRouteTestRoute
  '/$slug/(dashboard)/dashboard': typeof SlugdashboardDashboardRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/org/$': typeof ApiOrgSplatRoute
  '/$slug/(dashboard)/dashboard/': typeof SlugdashboardDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authed-route'
    | '/sign-in'
    | '/authed-route/test'
    | '/$slug/dashboard'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authed-route'
    | '/sign-in'
    | '/authed-route/test'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/dashboard'
  id:
    | '__root__'
    | '/'
    | '/authed-route'
    | '/sign-in'
    | '/authed-route/test'
    | '/$slug/(dashboard)/dashboard'
    | '/api/auth/$'
    | '/api/org/$'
    | '/$slug/(dashboard)/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRouteRoute: typeof AuthedRouteRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  SlugdashboardDashboardRoute: typeof SlugdashboardDashboardRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOrgSplatRoute: typeof ApiOrgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authed-route': {
      id: '/authed-route'
      path: '/authed-route'
      fullPath: '/authed-route'
      preLoaderRoute: typeof AuthedRouteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authed-route/test': {
      id: '/authed-route/test'
      path: '/test'
      fullPath: '/authed-route/test'
      preLoaderRoute: typeof AuthedRouteTestRouteImport
      parentRoute: typeof AuthedRouteRouteRoute
    }
    '/api/org/$': {
      id: '/api/org/$'
      path: '/api/org/$'
      fullPath: '/api/org/$'
      preLoaderRoute: typeof ApiOrgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/(dashboard)/dashboard': {
      id: '/$slug/(dashboard)/dashboard'
      path: '/$slug/dashboard'
      fullPath: '/$slug/dashboard'
      preLoaderRoute: typeof SlugdashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/(dashboard)/dashboard/': {
      id: '/$slug/(dashboard)/dashboard/'
      path: '/'
      fullPath: '/$slug/dashboard/'
      preLoaderRoute: typeof SlugdashboardDashboardIndexRouteImport
      parentRoute: typeof SlugdashboardDashboardRoute
    }
  }
}

interface AuthedRouteRouteRouteChildren {
  AuthedRouteTestRoute: typeof AuthedRouteTestRoute
}

const AuthedRouteRouteRouteChildren: AuthedRouteRouteRouteChildren = {
  AuthedRouteTestRoute: AuthedRouteTestRoute,
}

const AuthedRouteRouteRouteWithChildren =
  AuthedRouteRouteRoute._addFileChildren(AuthedRouteRouteRouteChildren)

interface SlugdashboardDashboardRouteChildren {
  SlugdashboardDashboardIndexRoute: typeof SlugdashboardDashboardIndexRoute
}

const SlugdashboardDashboardRouteChildren: SlugdashboardDashboardRouteChildren =
  {
    SlugdashboardDashboardIndexRoute: SlugdashboardDashboardIndexRoute,
  }

const SlugdashboardDashboardRouteWithChildren =
  SlugdashboardDashboardRoute._addFileChildren(
    SlugdashboardDashboardRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRouteRoute: AuthedRouteRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  SlugdashboardDashboardRoute: SlugdashboardDashboardRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOrgSplatRoute: ApiOrgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
