// biome-ignore-all format: generated
// This file is auto-generated by better-convex
// Do not edit manually. Run `better-convex codegen` to regenerate.

import { createApiLeaf } from "better-convex/server";
import type { inferApiInputs, inferApiOutputs } from "better-convex/server";
import { api as convexApi } from "../functions/_generated/api.js";


export const api = {
  _http: {
  },
} as const;

export type Api = typeof api;
export type ApiInputs = inferApiInputs<Api>;
export type ApiOutputs = inferApiOutputs<Api>;

