/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$"
import { Route as AuthedRouteRouteRouteImport } from "./routes/authed-route/route"
import { Route as AuthedRouteTestRouteImport } from "./routes/authed-route/test"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as SignInRouteImport } from "./routes/sign-in"

const SignInRoute = SignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => rootRouteImport
} as any)
const AuthedRouteRouteRoute = AuthedRouteRouteRouteImport.update({
  id: "/authed-route",
  path: "/authed-route",
  getParentRoute: () => rootRouteImport
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport
} as any)
const AuthedRouteTestRoute = AuthedRouteTestRouteImport.update({
  id: "/test",
  path: "/test",
  getParentRoute: () => AuthedRouteRouteRoute
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/authed-route": typeof AuthedRouteRouteRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/authed-route/test": typeof AuthedRouteTestRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/authed-route": typeof AuthedRouteRouteRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/authed-route/test": typeof AuthedRouteTestRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/authed-route": typeof AuthedRouteRouteRouteWithChildren
  "/sign-in": typeof SignInRoute
  "/authed-route/test": typeof AuthedRouteTestRoute
  "/api/auth/$": typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/authed-route"
    | "/sign-in"
    | "/authed-route/test"
    | "/api/auth/$"
  fileRoutesByTo: FileRoutesByTo
  to: "/" | "/authed-route" | "/sign-in" | "/authed-route/test" | "/api/auth/$"
  id:
    | "__root__"
    | "/"
    | "/authed-route"
    | "/sign-in"
    | "/authed-route/test"
    | "/api/auth/$"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRouteRoute: typeof AuthedRouteRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/sign-in": {
      id: "/sign-in"
      path: "/sign-in"
      fullPath: "/sign-in"
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/authed-route": {
      id: "/authed-route"
      path: "/authed-route"
      fullPath: "/authed-route"
      preLoaderRoute: typeof AuthedRouteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/authed-route/test": {
      id: "/authed-route/test"
      path: "/test"
      fullPath: "/authed-route/test"
      preLoaderRoute: typeof AuthedRouteTestRouteImport
      parentRoute: typeof AuthedRouteRouteRoute
    }
    "/api/auth/$": {
      id: "/api/auth/$"
      path: "/api/auth/$"
      fullPath: "/api/auth/$"
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteRouteRouteChildren {
  AuthedRouteTestRoute: typeof AuthedRouteTestRoute
}

const AuthedRouteRouteRouteChildren: AuthedRouteRouteRouteChildren = {
  AuthedRouteTestRoute: AuthedRouteTestRoute
}

const AuthedRouteRouteRouteWithChildren =
  AuthedRouteRouteRoute._addFileChildren(AuthedRouteRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRouteRoute: AuthedRouteRouteRouteWithChildren,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { createStart } from "@tanstack/react-start"
import type { getRouter } from "./router.tsx"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
